db.getCollection('suppliers').insertMany([
{	name: '信德', id: NumberInt(1)},
{	name: '海隆', id: NumberInt(2)},
{	name: '永昇', id: NumberInt(3)},
{	name: '大隆行', id: NumberInt(4)},
{	name: '興隆行', id: NumberInt(5)},
{	name: '細莊', id: NumberInt(6)},
{	name: '羅萬通', id: NumberInt(7)},
{	name: '恆豐', id: NumberInt(8)},
{	name: '聯興', id: NumberInt(9)},
{	name: '志成', id: NumberInt(10)},
{	name: '永榮', id: NumberInt(10)},
{	name: '生昌', id: NumberInt(11)},
{	name: '長豐', id: NumberInt(12)},
{	name: '華昌藥材行', id: NumberInt(13)},
{	name: '豐盛泰', id: NumberInt(14)},
{	name: '信裕', id: NumberInt(15)},
{	name: '啟發', id: NumberInt(16)},
{	name: '利豐', id: NumberInt(17)},
{	name: '華昌行', id: NumberInt(18)},
{	name: '林記', id: NumberInt(19)},
{	name: '振興', id: NumberInt(20)},
{	name: '正隆行', id: NumberInt(21)},
{	name: '合發', id: NumberInt(22)},
{	name: '耀昌', id: NumberInt(23)},
{	name: '德利', id: NumberInt(24)},
{	name: '源興', id: NumberInt(25)},
{	name: '志誠行', id: NumberInt(26)},
{	name: '東成', id: NumberInt(27)},
{	name: '利豐海產', id: NumberInt(28)},
{	name: '信興行', id: NumberInt(29)},
{	name: '廣大行', id: NumberInt(30)},
{	name: '長白山公司', id: NumberInt(31)},
{	name: '南聯', id: NumberInt(32), autoPaid: true},
{	name: '三喜', id: NumberInt(33), autoPaid: true},
{	name: '中興', id: NumberInt(34), autoPaid: true},
{	name: '時富(遠東)', id: NumberInt(35), autoPaid: true},
{	name: '自然里(香港)', id: NumberInt(36), autoPaid: true},
]);
